enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

cli-source = "MorpheApp/morphe-desktop"
cli-version = "dev"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "both"
version = "20.51.39"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.youtube"
apkpure-dlurl = "com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music-Extended]
enabled = true
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
version = "9.15.51"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.apps.youtube.music"
apkpure-dlurl = "com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
included-patches = "'Disable music video in album'" 

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
rv-brand = "Morphe"
build-mode = "both"
version = "21.04.223"
patches-source = "sashade8-ship-it/dual-vot-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.youtube"
apkpure-dlurl = "com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music-Morphe]
enabled = true
app-name = "YouTube Music"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
version = "9.15.51"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.apps.youtube.music"
apkpure-dlurl = "com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"