name: Sync with Template Repository

on:
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Template Repository as Upstream
        run: |
          git remote add upstream https://github.com/j-hc/revanced-magisk-module.git
          git fetch upstream

      - name: Merge Changes with Conflict Resolution
        run: |
          git merge upstream/main --allow-unrelated-histories --strategy-option theirs || true
          git add .
          git commit -m "Force merge upstream changes" || true

      - name: Create Pull Request for Changes
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync with Template Repository"
          branch: sync-upstream
          title: "Sync with Template Repository"
          body: "This PR includes changes from the upstream repository."
