name: Sync with Template Repository

on:
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name "MANCrimSon"
          git config --global user.email "MANCrimSon@users.noreply.github.com"

      - name: Add Template Repository as Upstream
        run: |
          git remote add upstream https://github.com/j-hc/revanced-magisk-module.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push origin main
